version: '3.7'
services:
    postgres:
        image: postgres:14
        restart: always
        environment:
          - POSTGRES_DB=block-explorer-dev
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
        container_name: "block-explorer-dev"